# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI with Ant

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 20
      uses: actions/setup-java@v2
      with:
        java-version: '20'
        distribution: 'adopt'

    - name: Install Apache Ant
      run: sudo apt-get install -y ant

    - name: Build with Ant
      run: ant -f build.xml jar

    - name: Run the application
      run: java -jar build/Calculator.jar
